### ISSUE TITLE
initialize tracker model

### ISSUE THREAD

**Issue by Rostiferr** [AIRLegend/aitrack#237]
Hi there I am going to be as clear as possible when trying to describe the problem I am having 
i have been using aitrack now for a few months with no issues absolutely amazing and then this morning when i go to try and open it again this happens 

When I open aitrack, a window pops up with 'No camera detected. Plug one in and restart the program. 
so this list below is what i did to try and fix it.

- [x] Unplug and plug the camera back in
- [x] check that a Windows update hasn't changed and file private settings
- [x] check to make sure that my camera is allowing the use off aitrack but this doesn't show on the options for me 

so after this, i think cool ill try it again, and then I get another window that immediately pops up after that first one saying ''there was a problem initializing the tracker. Check the modules folder and then restart the program'. 

so i do nothing changes, no I've tried looking on credit forums and other places to trouble shoot it but I have just been stuck in the mud any help here would be greatly appreciated.

**To Reproduce**
